homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('about_me/', views.about_me, name='about_me'),
    path('mmrs/', views.mmrs, name='mmrs'),
    path('socmed/', views.socmed, name='socmed'),

    # dilanjutkan ...
]

jadwal/urls.py
from django.urls import path
from .views import join, delete, detail

app_name = 'jadwal'

urlpatterns = [
    path('', join, name='Schedule'),
    path('<int:pk>', delete, name = 'delete'),
    path('detail/<int:pk>', detail, name='detail'),
    
    # path('profile/', views.profile, name='profile'),
    # dilanjutkan ...
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
    # ('profile/', views.profile, name='profile'),
    # dilanjutkan ...
]

story_4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('story1.urls')),
    path('jadwal/', include('jadwal.urls')),
    
]

homepage/models.py
from django.db import models

# Create your models here.

jadwal/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
    matkul = models.CharField(blank=False, max_length= 100)
    dosen = models.CharField(blank=False, max_length= 100)
    sks = models.IntegerField(blank=False)
    deskripsi = models.CharField(blank=False, max_length= 150)
    semester = models.CharField(blank=False, max_length= 150)
    kelas = models.CharField(blank=False, max_length= 150, help_text ='Masukkan tahun semester, e.g 2020/2021')

story1/models.py
from django.db import models

# Create your models here.

jadwal/forms.py
from django import forms

class SchedForm(forms.Form):
    matkul = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Mata Kuliah',
        'type' : 'text',
        'required' : True,
    }))
    dosen = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Dosen',
        'type' : 'text',
        'required' : True,
    }))
    sks = forms.IntegerField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Jumlah sks',
        'type' : 'text',
        'required' : True,
    }))
    deskripsi = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Deskripsi Mata Kuliah',
        'type' : 'text',
        'required' : True,
    }))
    semester = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Semester',
        'type' : 'text',
        'required' : True,
    }))
    kelas = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Kelas',
        'type' : 'text',
        'required' : True,
    }))

homepage/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about_me(request):
    return render(request, 'about_me.html')

def mmrs(request):
    return render(request, 'mmrs.html')

def socmed(request):
    return render(request, 'socmed.html')

jadwal/views.py
from django.shortcuts import render, redirect
from .models import Schedule as jadwal
from .forms import SchedForm

# Create your views here.
def join(request):
    if request.method == 'POST':
        form = SchedForm(request.POST)
        if form.is_valid():
            schd = jadwal()
            schd.matkul = form.cleaned_data['matkul']
            schd.dosen = form.cleaned_data['dosen']
            schd.sks = form.cleaned_data['sks']
            schd.deskripsi = form.cleaned_data['deskripsi']
            schd.semester = form.cleaned_data['semester']
            schd.kelas = form.cleaned_data['kelas']
            schd.save() 
        return redirect("/jadwal")

    else:
        schd = jadwal.objects.all()
        form = SchedForm()
        response = {'schd':schd, 'form': form}
        return render(request, 'jadwal.html', response)

def delete(request, pk):
    if request.method == 'POST':
        form = SchedForm(request.POST)
        if form.is_valid():
            schd = jadwal()
            schd.matkul = form.cleaned_data['matkul']
            schd.dosen = form.cleaned_data['dosen']
            schd.sks = form.cleaned_data['sks']
            schd.deskripsi = form.cleaned_data['deskripsi']
            schd.semester = form.cleaned_data['semester']
            schd.kelas = form.cleaned_data['kelas']
            schd.save() 
        return redirect("/jadwal")
    else:
            jadwal.objects.filter(pk = pk).delete()
            data = jadwal.objects.all()
            form = SchedForm()
            response = {
                "schd" : data,
                "form": form
            }
            return render(request, 'jadwal.html', response)

def detail(request, pk):
    matkul = jadwal.objects.get(pk=pk)
    response1= {
        "matkul" : matkul,
    }
    return render(request, 'detail.html', response1)

story1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

homepage/templates/about_me.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Story 3</title>
    {% include "navbar.html" %} 
  <br>
  <br>
    <div class="container">
    <div class="row">
          <div class="col-sm-4">
            <div id="profile2">
                <img class= "img-responsive" src= "{% static 'profile.PNG' %}" alt="Profile" width="260" height="260"/>
            </div>
            <div id="hanifa">
                <h3>Hanifa &nbsp;Ariana</h3>
                <h5 style="padding-left: 5%;">3rd August 2001<h5>

            </div>
        </div>
          <div class="col-sm-8">
              <div id="bio">
                  <h4 style="text-align: justify; font-weight: bold;">H O B B Y</h4>
                  <p style="text-align: justify;">Listening to music</p>
                  <br>
                  <h4 style="text-align: justify; font-weight: bold;">E D U C A T I O N</h4>
                  
                  <div class="table-responsive-sm">
                  <table style="width:70%" id="edu">
                    <tr>
                        <td>SMPN 99 Jakarta</td>
                        <td>2013 — 2016</td>
                    </tr>
                    <tr>
                        <td>SMAN 68 Jakarta</td>
                        <td>2016 — 2019</td>
                    </tr>
                    <tr>
                        <td>Faculty of Computer Science, UI</td>
                        <td>2019 — present</td>
                    </tr>
                </table>
            </div>
                <br>
                <h4 style="text-align: justify; font-weight: bold;">E X P E R I E N C E S</h4>
                <p>Staff of Public Relations OH Fasilkom UI 2019</p>
                <p>Staff of Public Relations Wisuda Ganjil Fasilkom 2020</p>
                <p>Staff of Public Relations BEM Fasilkom UI 2020</p>
                <p>Staff of Business Development PERAK Fasilkom 2020</p>
                <p>Staff of Secretary COMPFEST 2020</p>
            </div>
        </div>
    </div>
</div>
  <br>
  <br>
  <br>
    </body>
</html> 

homepage/templates/home.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Story 3</title>
        <body>
        {% include "navbar.html" %} 

  <br>
<br>
    <div id="profile">
        <img class= "img-responsive" src= "{% static 'profile2.PNG' %}" alt="Profile" width="300" height="300" style="display: block; margin: auto;" />

    </div>
<br>

    <div id="hello">
  
        <img class= "img-responsive" src= "{% static 'hello.png' %}" alt="Hello" width="300" height="300" style="display: block; margin: auto;"/>
    </div>
    <br>


    </div> 
    
</body>
</html>

homepage/templates/mmrs.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
    <title>Story 3</title>
    <body>
    {% include "navbar.html" %} 
    <div class="container">
        <div class="row" style="width: 100%";>
                <div class="col-sm-4">
                    <div id="kiri">
                        <img src= "{% static 'balii.jpg' %}" alt="perpis" width="280" height="210"/>
                        <p>BALI 2018&nbsp;</p>
                        <img src= "{% static 'tamling.jpg' %}" alt="tamling" width="280" height="210"/>
                        <p>KAMABA 2019</p>
                        <img src= "{% static 'bakar.jpg' %}" alt="tamling" width="280" height="210"/>
                        <p>TAHUN BARU 2020</p>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div id="tengah">
                        <img src= "{% static 'tk.jpg' %}" alt="bazkom" width="280" height="210"/>
                        <p>2019</p>  
                        <img src= "{% static 'jakun.jpg' %}" alt="jakun" width="280" height="210"/>
                        <p>JAKET KUNING</p>
                        <img src= "{% static 'liga.jpg' %}" alt="liga" width="280" height="210"/>
                        <p>LIGA PERAK 2020</p>
                        
                    </div>
                </div>
                <div class="col-sm-4">
                    <div id="kanan">
                        <img src= "{% static 'sma.jpg' %}" alt="sma" width="280" height="210"/>
                        <p>WISUDA 2019</p>
                        <img src= "{% static 'parade.jpg' %}" alt="Parade" width="280" height="210"/>
                        <p>PARADE OLIM 2019</p>
                        <img src= "{% static 'bisdev.jpg' %}" alt="bisdev" width="280" height="210"/>
                        <p>TEAM BUILDING PERAK 2020</p>
                    </div>
                </div>
              </div>

        </div>
    </div>
    </body>
</html>

homepage/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Hanifa Ariana</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <link href="{% static 'bootstrap2.css' %}" rel="stylesheet" type="text/css">
      </head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top nav justify-content-center" style="background-color: #EADBDB;">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="{% url 'homepage:home' %}"><img src="{% static 'logo.png' %}" width="50px" height="50px" style="text-align: left;" ></a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'homepage:home' %}" style="color: black;"> H O M E </a></li>
          <li><a href="{% url 'homepage:about_me' %}" style="color: black;"> A B O U T &nbsp;M E</a></li>
          <li><a href="{% url 'homepage:socmed' %}" style="color: black;"> S O C I A L &nbsp;M E D I A </a></li>
          <li><a href="{% url 'homepage:mmrs' %}" style="color: black;"> M E M O R I E S </a></li>
          <li><a href="{% url 'story1:index' %}" style="color: black;"> S T O R Y &nbsp;1  </a></li>
          <li><a href="{% url 'jadwal:Schedule' %}" style="color: black;"> J A D W A L </a></li>

        </ul>
      </div>
    </div>
  </nav>
</body>

homepage/templates/socmed.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Story 3</title>
        <body>
        {% include "navbar.html" %} 
      <br>
      <br>
      <br>
      <br>
<br>
<br>

      <div id="socmed">
        <a href="https://www.instagram.com/hanifariana/" target="_blank">
            <img src="{% static 'ig.png' %}" alt="Ig @hanifariana" width="150" height="150" hspace="20"/>
        </a>
        <a href="https://www.twitter.com/hanifariana/" target="_blank">
            <img src="{% static 'twitter.png' %}" alt="Twitter @hanifariana" width="150" height="150" hspace="20"/>
        </a>
        <a href="https://www.linkedin.com/in/hanifa-ariana-8832a61a0/" target="_blank">
            <img src="{% static 'linkedin.png' %}" alt="LinkedIn Hanifa Ariana" width="150" height="150" hspace="20"/>
        </a>
        <a href="https://open.spotify.com/user/hanifariana?si=_rDme1xBSb6GCyol1DDNWw" target="_blank">
            <img src="{% static 'spotify.png' %}" alt="Spotify Hanifa Ariana" width="150" height="150" hspace="20"/>
        </a>
      </div>
      </body>
</html>

jadwal/templates/detail.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Story 5</title>
        <body>
        {% include "navbar.html" %} 
        <div class="container">
            
        <h1 style="text-align: center;">D E T A I L</h1>
        <a href="{% url 'jadwal:Schedule' %}">B A C K</a>
        <!-- <a href="jadwal/">B A C K</a> -->
            <div class="row">
                <div class="col">
                    <form action='' method="POST">
                        {% csrf_token %}
                        {{ form }}
                        <br>
                    </form>
                </div> 
                <div class="col">
                    <table class="table">
                        <thead>
                        <tr>
                           <th scope="col">Mata Kuliah</th>
                           <th scope="col">Dosen</th>
                           <th scope="col">SKS</th>
                           <th scope="col">Deskripsi</th>
                           <th scope="col">Semester</th>
                           <th scope="col">Kelas</th>
                        </tr>
                    </thead>
                    <br>
                    <tbody>
                        <tr>
                            <th scope="row">{{matkul.matkul}}</th>
                            <td>{{matkul.dosen}}</td>
                            <td>{{matkul.sks}}</td>
                            <td>{{matkul.deskripsi}}</td>
                            <td>{{matkul.semester}}</td>
                            <td>{{matkul.kelas}}</td>
                </tr>
                </tbody>
            </table>     
                </div>
            </div>
            </div>
        </body>      

jadwal/templates/jadwal.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Story 5</title>
        <body>
        {% include "navbar.html" %} 
        <div class="container">
        <h1 style="text-align: center;">S C H E D U L E</h1>
            <div class="row">
                <div class="col-sm-6">
                        <form action='' method="POST">
                            {% csrf_token %}
                            {{ form }}
                            <br>
                            <div class="centre-items">
                                <input type="submit" class="btn btn-primary" value="Add Schedule" style="background-color: black; border-color: black;">
                            </div>
                        </form>
                </div>
                  <div class="col-sm-6">
                    <table class="table">
                        <thead>
                        <tr>
                           <th scope="col">Mata Kuliah</th>
                        </tr>
                    </thead>
                    <br>
                    <tbody>
                        {% for jadwal in schd %}
                        <tr>
                            <th scope="row">{{jadwal.matkul}}</th>
                            <td><a href="{% url 'jadwal:delete' pk=jadwal.pk %}"><button class="btn btn-icon btn-danger"><i class="fa fa-trash"></i>Delete</button></a></td>
                            <td><a href="{% url 'jadwal:detail' pk=jadwal.pk %}"> <button class="btn btn-info">Detail</button></a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
                      </div>
                  </div>
        </body>

story1/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'style.css' %}"/>
    <title>My Personal Page</title>
    {% include "navbar.html" %} 
    
</head>
<body>
    <div id="header">
        <h1>My Personal Page</h1>
    </div>

    <div id="profile">
        <img src="{% static 'profile2.PNG' %}" alt="Profile" width="200" height="200" align="center"/>
        <h1>Hanifa Ariana</h1>
    </div>
    
    <div id="main">
        <h3>֍֍֍֍֍֍֍֍֍֍֍</h3>
        <h2>A B O U T &nbsp;&nbsp;&nbsp; M E</h2>
        <p>An ESFP-A person who likes to explore new experiences and enjoy to meet new people ヽ(*⌒▽⌒*)ﾉ.</p>
        <div id="table1">
        <table style="width:190%">
            <tr>
                <td>NPM</td>
                <td>1906306092</td>
            </tr>
            <tr>
                <td>Student of</td>
                <td>Fasilkom UI 2019</td>
            </tr>
            <tr>
                <td>Hobby</td>
                <td>Listening to music</td>
            </tr>
        </table>
    </div>
    <br>

        <div id="edu">
        <h3>Educations</h3>
        <table style="width:102%">
            <tr>
                <td>SMPN 99 Jakarta</td>
                <td>2013 — 2016</td>
            </tr>
            <tr>
                <td>SMAN 68 Jakarta</td>
                <td>2016 — 2019</td>
            </tr>
            <tr>
                <td>Faculty of Computer Science, UI</td>
                <td>2019 — present</td>
            </tr>
        </table>
        </div>
        <h3>֍֍֍֍֍֍֍֍֍֍֍</h3>

    </div>

    <div id="socmed">
        <h2>More Info</h2>
        <a href="https://www.instagram.com/hanifariana/" target="_blank">
            <img src="{% static 'ig.png' %}" alt="Ig @hanifariana" width="50" height="50" hspace="20"/>
        </a>
        <a href="https://www.twitter.com/hanifariana" target="_blank">
            <img src="{% static 'twitter.png' %}" alt="Twitter @hanifariana" width="50" height="50" hspace="20"/>
        </a>
        <a href="https://www.linkedin.com/in/hanifa-ariana-8832a61a0/" target="_blank">
            <img src="{% static 'linkedin.png' %}" alt="LinkedIn Hanifa Ariana" width="50" height="50" hspace="20" />
        </a>
        <a href="https://open.spotify.com/user/hanifariana?si=_rDme1xBSb6GCyol1DDNWw" target="_blank">
            <img src="{% static 'spotify.png' %} " alt="Spotify Hanifa Ariana" width="50" height="50" hspace="20"/>
        </a>
    </div>
</body>

<footer>
    <p>© 2020 Hanifa Ariana</p>
</footer>
</html>